# Generated by Django 5.2.4 on 2025-08-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booksvariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('MYS', 'Mystery'), ('SCI', 'Science'), ('BIO', 'Biography'), ('ROM', 'Romance'), ('FANT', 'Fantasy'), ('HIS', 'History')], max_length=10)),
            ],
        ),
    ]
